/* Generated By:JJTree: Do not edit this line. ASTConstTerm.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
import java.util.*;

public class ASTConstTerm extends SimpleNode {
  List<String> ops;

  public ASTConstTerm(int id) {
    super(id);
  }

  public ASTConstTerm(Env p, int id) {
    super(p, id);
  }

  public void setOps(List<String> o) {
    ops = new ArrayList(o);
  }

  public List<String> getOps() {
    return ops;
  }

  public String getOps(int i) {
    return ops.get(i);
  }

  public String toString() {
    return "ConstTerm: " + ops;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EnvVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00888de0ec225bc333ec3b24d83f25d4 (do not edit this line) */
