/* Generated By:JavaCC: Do not edit this line. EnvVisitor.java Version 4.1d1 */
public interface EnvVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRoot node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTPrimeVar node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTTerm node, Object data);
  public Object visit(ASTFactor node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTTypeDef node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTRange node, Object data);
  public Object visit(ASTConstExpression node, Object data);
  public Object visit(ASTConstTerm node, Object data);
  public Object visit(ASTConstFactor node, Object data);
}
/* JavaCC - OriginalChecksum=3b79d756df11abc31ab637465302b4ad (do not edit this line) */
