/* Generated By:JJTree: Do not edit this line. ASTConstExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConstExpression extends SimpleNode {
  public ASTConstExpression(int id) {
    super(id);
  }

  public ASTConstExpression(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ee9795eb2da4ccb691c8a4700462082 (do not edit this line) */
