/* Generated By:JJTree: Do not edit this line. ASTConstPrimary.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConstPrimary extends SimpleNode {
  public ASTConstPrimary(int id) {
    super(id);
  }

  public ASTConstPrimary(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c16ce65115baabf6a28d16da9790500 (do not edit this line) */
