/* Generated By:JJTree: Do not edit this line. ASTConstTerm.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTConstTerm extends SimpleNode {
  public ASTConstTerm(int id) {
    super(id);
  }

  public ASTConstTerm(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3109d8e064ccf0a04e259711b1206fc2 (do not edit this line) */
