/* Generated By:JJTree: Do not edit this line. ASTNeg.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTNeg extends SimpleNode {
  public ASTNeg(int id) {
    super(id);
  }

  public ASTNeg(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e83e0c7defe45f2b7adbffe2daa4439b (do not edit this line) */
