/* Generated By:JJTree: Do not edit this line. ASTPos.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPos extends SimpleNode {
  public ASTPos(int id) {
    super(id);
  }

  public ASTPos(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=427ab505bbd0e097b47f91e0ecae5770 (do not edit this line) */
