/* Generated By:JJTree: Do not edit this line. ASTRange.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRange extends SimpleNode {
  public ASTRange(int id) {
    super(id);
  }

  public ASTRange(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3cf5fd4101d0311e6540cc85b5eb9a0 (do not edit this line) */
