/* Generated By:JJTree: Do not edit this line. ASTRoot.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRoot extends SimpleNode {
  public ASTRoot(int id) {
    super(id);
  }

  public ASTRoot(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=12a7d9a77cb401d96dc094315713dc76 (do not edit this line) */
