/* Generated By:JJTree: Do not edit this line. ASTTypeDef.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTypeDef extends SimpleNode {
  public ASTTypeDef(int id) {
    super(id);
  }

  public ASTTypeDef(Env p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c248219414d6ff8c2e34007d92801a9 (do not edit this line) */
