/* Generated By:JavaCC: Do not edit this line. EnvTreeConstants.java Version 4.1d1 */
public interface EnvTreeConstants
{
  public int JJTROOT = 0;
  public int JJTASSIGNMENT = 1;
  public int JJTVAR = 2;
  public int JJTPRIMEVAR = 3;
  public int JJTVOID = 4;
  public int JJTEXPRESSION = 5;
  public int JJTTERM = 6;
  public int JJTFACTOR = 7;
  public int JJTINTEGER = 8;
  public int JJTFLOAT = 9;
  public int JJTTYPEDEF = 10;
  public int JJTTYPE = 11;
  public int JJTRANGE = 12;
  public int JJTCONSTEXPRESSION = 13;
  public int JJTCONSTTERM = 14;
  public int JJTCONSTFACTOR = 15;


  public String[] jjtNodeName = {
    "Root",
    "Assignment",
    "Var",
    "PrimeVar",
    "void",
    "Expression",
    "Term",
    "Factor",
    "Integer",
    "Float",
    "TypeDef",
    "Type",
    "Range",
    "ConstExpression",
    "ConstTerm",
    "ConstFactor",
  };
}
/* JavaCC - OriginalChecksum=4637e2216380759c0b865f18a27e5466 (do not edit this line) */
