/* Generated By:JJTree: Do not edit this line. ASTConstExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
import java.util.*;

public class ASTConstExpression extends SimpleNode {
  List<String> ops;

  public ASTConstExpression(int id) {
    super(id);
  }

  public ASTConstExpression(Env p, int id) {
    super(p, id);
  }

  public void setOps(List<String> o) {
    ops = new ArrayList(o);
  }

  public List<String> getOps() {
    return ops;
  }

  public String getOps(int i) {
    return ops.get(i);
  }

  public String toString() {
    return "ConstExpression: " + ops;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EnvVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cad607194e77ec6690779f540f350e4b (do not edit this line) */
