/* Generated By:JJTree: Do not edit this line. ASTRange.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRange extends SimpleNode {
  private DataType type;

  public ASTRange(int id) {
    super(id);
  }

  public ASTRange(Env p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(EnvVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d984f8d4b905179bfec4bfec7663c6fd (do not edit this line) */
