/* Generated By:JJTree: Do not edit this line. ASTTypeDef.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTypeDef extends SimpleNode {
  public ASTTypeDef(int id) {
    super(id);
  }

  public ASTTypeDef(Env p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EnvVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69631a395d3713376ccf3d100122dbe3 (do not edit this line) */
