/* Generated By:JJTree&JavaCC: Do not edit this line. EnvConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EnvConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLABEL = 4;
  /** RegularExpression Id. */
  int FLOATLABEL = 5;
  /** RegularExpression Id. */
  int BOOLLABEL = 6;
  /** RegularExpression Id. */
  int VARLABEL = 7;
  /** RegularExpression Id. */
  int INF = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int WORD = 15;
  /** RegularExpression Id. */
  int PRIMEWORD = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"Int\"",
    "\"Float\"",
    "\"Bool\"",
    "\"var\"",
    "\"infinity\"",
    "\"true\"",
    "\"false\"",
    "<DIGIT>",
    "<INTEGER>",
    "<FLOAT>",
    "<LETTER>",
    "<WORD>",
    "<PRIMEWORD>",
    "\"\\n\"",
    "\"\\r\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"..\"",
  };

}
